tracked_abilities = set([ 
#Terran
            'Command Center',
			'Upgrade to CommandCenter',
			'Upgrade to OrbitalCommand',
			'Upgrade to PlanetaryFortress',
			'Cancel upgrade to CommandCenter',
			'Cancel upgrade to OrbitalCommand',
			'Cancel upgrade to PlanetaryFortress',
			'Construct Reactor',
			'Construct Techlab',
			'Upgrade to PlanetaryFortress',
            'Supply Depot',
            'Barracks',
            'Engineering Bay',
            'Missile Turret',
            'Bunker',
            'Refinery',
            'Sensor Tower',
            'Ghost Academy',
            'Factory',
            'Starport',
            'Armory',
            'Fusion Core',
            'Train SCV',
            'MULE (Target)',
            'MULE (Location)',
            'Extra Supplies',
            'Scanner Sweep',
            'Hi-Sec Auto Tracking',
            'Building Armor',
            'Infantry Weapons Level 1',
            'Infantry Weapons Level 2',
            'Infantry Weapons Level 3',
            'Neosteel Frame',
            'Infantry Armor Level 1',
            'Infantry Armor Level 2',
            'Infantry Armor Level 3',
            'Arm silo with Nuke',
            'Personal Cloaking',
            'Moebius Reactor',
            'Salvage',
            'Vehicle Plating Level 1',
            'Vehicle Plating Level 2',
            'Vehicle Plating Level 3',
            'Vehicle Weapons Level 1',
            'Vehicle Weapons Level 2',
            'Vehicle Weapons Level 3',
            'Ship Plating Level 1',
            'Ship Plating Level 2',
            'Ship Plating Level 3',
            'Ship Weapons Level 1',
            'Ship Weapons Level 2',
            'Ship Weapons Level 3',
            'Marine',
            'Reaper',
            'Ghost',
            'Marauder',
			'Nitro Packs',
			'Stimpack',
			'Combat Shields',
			'Concussive Shells',
            'Siege Tank',
            'Thor',
            'Hellion',
			'Siege Tech',
			'Infernal Pre-igniter',
			'250mm Strike Cannons',
			'Cancel Research',
			'Cancel specific Research',
            'Medivac',
            'Banshee',
            'Raven',
            'Battlecruiser',
            'Viking',
			'Cloaking Field',
			'Caduceus Reactor',
			'Corvid Rector',
			'Seeker Missile',
			'Durable Materials',
#Protoss
            'Nexus',
            'Pylon',
            'Gateway',
            'Forge',
            'Fleet Beacon',
            'Twilight Council',
            'Photon Cannon',
            'Assimilator',
            'Stargate',
            'Templar Archives',
            'Dark Shrine',
            'Robotics Bay',
            'Robotics Facility',
            'Cybernetics Core',
            'Hallucinate Archon',
            'Hallucinate Colossus',
            'Hallucinate High Templar',
            'Hallucinate Immortal',
            'Hallucinate Phoenix',
            'Hallucinate Probe',
            'Hallucinate Stalker',
            'Hallucinate Void Ray',
            'Hallucinate Warp Prism',
            'Hallucinate Zealot',
            'Probe',
            'Mothership',
            'Chrono Boost',
            'Train Zealot',
            'Train Stalker',
            'Train High Templar',
            'Train Dark Templar',
            'Train Sentry',
			'Warp in Zealot',
			'Warp in Stalker',
			'Warp in High Templar',
			'Warp in Dark Templar',
			'Warp in Sentry',
			'Tranform to Warpgate',
			'Tranform to Gateway',
            'Ground Weapons Level 1',
            'Ground Weapons Level 2',
            'Ground Weapons Level 3',
            'Ground Armor Level 1',
            'Ground Armor Level 2',
            'Ground Armor Level 3',
            'Shield Level 1',
            'Shield Level 2',
            'Shield Level 3',
            'Air Weapons Level 1',
            'Air Weapons Level 2',
            'Air Weapons Level 3',
            'Air Armor Level 1',
            'Air Armor Level 2',
            'Air Armor Level 3',
            'Warp Gate',
            'Hallucination',
            'Warp Prism',
            'Observer',
            'Colossus',
            'Immortal',
            'Phoenix',
            'Carrier',
            'Void Ray',
            'Charge',
            'Blink',
            'Graviton Catapult',
            'Khaydarin Amulet',
            'Psionic Storm',
            'Gravitic Booster',
            'Gravitic Drive',
            'Extended Thermal Lance',
#Zerg
            'Drone',
            'Zergling',
            'Overlord',
            'Hydralisk',
            'Mutalisk',
            'Ultralisk',
            'Roach',
            'Infestor',
            'Corruptor',
            'Hatchery',
            'Spawning Pool',
            'Evolution Chamber',
            'Hydralisk Den',
            'Spire',
            'Ultralisk Cavern',
            'Extractor',
            'Infestation Pit',
            'Nydus Network',
            'Baneling Nest',
            'Roach Warren',
            'Spine Crawler',
            'Spore Crawler',
            'Creep Tumor',
            'Larva',
            'Transfuse',
            'Queen',
            'Evolve Burrow',
            'Evolve Pneumatized Carapace',
            'Evolve Ventral Sacs',
			'Morph to Broodlord',
			'Morph to Overseer',
			'Morph to Baneling',
			'Cancel Morph to Broodlord',
			'Cancel Morph to Overseer',
			'Cancel Morph to Broodlord',
			'Upgrade to Spire',
			'Upgrade to Lair',
			'Upgrade to Hatchery',
			'Cancel upgrade to Spire',
			'Cancel upgrade to Lair',
			'Cancel upgrade to Hatchery',
            'Evolve Adrenal Glands',
            'Evolve Metabolic Boost',
            'Evolve Melee Attacks Level 1',
            'Evolve Melee Attacks Level 2',
            'Evolve Melee Attacks Level 3',
            'Evolve Ground Carapace Level 1',
            'Evolve Ground Carapace Level 2',
            'Evolve Ground Carapace Level 3',
            'Evolve Missile Attacks Level 1',
            'Evolve Missile Attacks Level 2',
            'Evolve Missile Attacks Level 3',
            'Evolve Glial Reconstitution',
            'Evolve Tunneling Claws',
            'Evolve Centrifugal Hooks',
            'Evolve Pathogen Glands',
            'Evolve Neural Parasite',
            'Spawn Nydus Worm',
            'Evolve Flyer Attacks Level 1',
            'Evolve Flyer Attacks Level 2',
            'Evolve Flyer Attacks Level 3',
            'Evolve Flyer Carapace Level 1',
            'Evolve Flyer Carapace Level 2',
            'Evolve Flyer Carapace Level 3',
            'Chitinous Plating',
])

tracked_building_orders = set([
#Terran
    'Command Center',
    'Supply Depot',
    'Barracks',
    'Engineering Bay',
    'Refinery',
    'Ghost Academy',
    'Factory',
    'Starport',
    'Armory',
    'Fusion Core',
    'Infantry Weapons Level 1',
    'Infantry Weapons Level 2',
    'Infantry Weapons Level 3',
    'Infantry Armor Level 1',
    'Infantry Armor Level 2',
    'Infantry Armor Level 3',
    'Vehicle Plating Level 1',
    'Vehicle Plating Level 2',
    'Vehicle Plating Level 3',
    'Vehicle Weapons Level 1',
    'Vehicle Weapons Level 2',
    'Vehicle Weapons Level 3',
    'Ship Plating Level 1',
    'Ship Plating Level 2',
    'Ship Plating Level 3',
    'Ship Weapons Level 1',
    'Ship Weapons Level 2',
    'Ship Weapons Level 3',
    'Stimpack',
    'Combat Shields',
    'Concussive Shells',
    'Infernal Pre-igniter',
    'Siege Tech',
    'Cloaking Field',
    'Arm silo with Nuke',
    'Personal Cloaking',
    'Moebius Reactor',
#Protoss
    'Nexus',
    'Pylon',
    'Gateway',
    'Forge',
    'Fleet Beacon',
    'Twilight Council',
    'Photon Cannon',
    'Assimilator',
    'Stargate',
    'Templar Archives',
    'Dark Shrine',
    'Robotics Bay',
    'Robotics Facility',
    'Cybernetics Core',
    'Ground Weapons Level 1',
    'Ground Weapons Level 2',
    'Ground Weapons Level 3',
    'Ground Armor Level 1',
    'Ground Armor Level 2',
    'Ground Armor Level 3',
    'Shield Level 1',
    'Shield Level 2',
    'Shield Level 3',
    'Air Weapons Level 1',
    'Air Weapons Level 2',
    'Air Weapons Level 3',
    'Air Armor Level 1',
    'Air Armor Level 2',
    'Air Armor Level 3',
    'Warp Gate',
    'Hallucination',
    'Charge',
    'Blink',
    'Psionic Storm',
    'Gravitic Booster',
    'Gravitic Drive',
    'Extended Thermal Lance',
#Zerg
    'Hatchery',
    'Spawning Pool',
    'Evolution Chamber',
    'Hydralisk Den',
    'Spire',
    'Ultralisk Cavern',
    'Extractor',
    'Infestation Pit',
    'Nydus Network',
    'Baneling Nest',
    'Roach Warren',
    'Creep Tumor',
    'Evolve Burrow',
    'Evolve Pneumatized Carapace',
    'Evolve Ventral Sacs',
    'Upgrade to Spire',
    'Upgrade to Lair',
    'Evolve Adrenal Glands',
    'Evolve Metabolic Boost',
    'Evolve Melee Attacks Level 1',
    'Evolve Melee Attacks Level 2',
    'Evolve Melee Attacks Level 3',
    'Evolve Ground Carapace Level 1',
    'Evolve Ground Carapace Level 2',
    'Evolve Ground Carapace Level 3',
    'Evolve Missile Attacks Level 1',
    'Evolve Missile Attacks Level 2',
    'Evolve Missile Attacks Level 3',
    'Evolve Glial Reconstitution',
    'Evolve Tunneling Claws',
    'Evolve Centrifugal Hooks',
    'Evolve Pathogen Glands',
    'Evolve Neural Parasite',
    'Evolve Flyer Attacks Level 1',
    'Evolve Flyer Attacks Level 2',
    'Evolve Flyer Attacks Level 3',
    'Evolve Flyer Carapace Level 1',
    'Evolve Flyer Carapace Level 2',
    'Evolve Flyer Carapace Level 3',
    'Chitinous Plating',
])
